### PR TITLE
patch script for 3403

### PR DESCRIPTION
**Pull request by wangcongheng**
Patching script for 3403

### CODE REVIEW

**Comment by wangcongheng** [comment]
please approve

**Comment by wangcongheng** [comment]
please approve

**Review by hsqianpin — CHANGES_REQUESTED** [review]
1. This is surface level patch, underlying root problem is still lurking somewhere in the ETL. But OK due to urgency will allow this to hardcoding to go ahead.
2. Please add in "internal_comment" and remember to update the **MODIFICATION** table (id='9304D59F-0CBD-4855-810B-E2ACB19B56CE')
CONCAT(internal_comment, char(13), CAST(GETDATE() as DATE),': Brute force changing _is_past_relationship_= '0' to align with CTOS report')
3. Modification_user can use 'BDDB8000-DB42-49AF-9937-9DE6E1FF4CC2' for the time-being since your account isn't available yet

**Comment by wangcongheng** [comment]
amended

**Review by hsqianpin — APPROVED** [review]
Very nice

**Pull request merged**
